services:
  facebook.user:
    class: BIT\SocialUserBundle\Security\User\Provider\FacebookProvider
    arguments:
      facebook: @bit_facebook.api
      validator: @validator
      userManager: @fos_user.user_manager
      socialUserManager: @bit_social_user