services:
  bit_social_user:
    class: BIT\SocialUserBundle\Controller\SocialUserControllerService
    arguments:
        config:
          functionsName: %bit_social_user.functionsName%
          defaultValues: %bit_social_user.defaultValues%
          defaultRole: %bit_social_user.defaultRole%
          setRoleAsSocialName: %bit_social_user.setRoleAsSocialName%
          mappingFQCN: %bit_social_user.mappingFQCN%
    calls:
      - [ setContainer, [ @service_container ] ]