services:
  bit_social_user:
    class: BIT\BITSocialUserBundle\Controller\SocialUserControllerService
    calls:
      - [ setContainer, [ @service_container ] ]
      
  kernel.listener.bit_social_security:
    class: BIT\BITSocialUserBundle\Listeners\SocialUserListener
    arguments: [@session, @security.context, @doctrine.orm.entity_manager]
    tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 0 }
        
  facebook.user:
      class: BIT\BITSocialUserBundle\Security\User\Provider\FacebookProvider
      arguments:
          facebook: @fos_facebook.api
          validator: @validator
          userManager: @fos_user.user_manager
          socialUserManager: @bit_social_user
  twitter.user:
      class: BIT\BITSocialUserBundle\Security\User\Provider\TwitterProvider
      arguments:
          twitter_oauth: @fos_twitter.api
          validator: @validator
          session: @session
          userManager: @fos_user.user_manager
          socialUserManager: @bit_social_user
  google.user:
      class: BIT\BITSocialUserBundle\Security\User\Provider\GoogleProvider
      arguments:
          google: @fos_google.api
          validator: @validator
          userManager: @fos_user.user_manager
          socialUserManager: @bit_social_user