services:
  twitter.user:
    class: BIT\SocialUserBundle\Security\User\Provider\TwitterProvider
    arguments:
      twitter_oauth: @bit_twitter.api
      validator: @validator
      session: @session
      userManager: @fos_user.user_manager
      socialUserManager: @bit_social_user